# -*- mode: python ; coding: utf-8 -*-
# Generated by: pyi-makespec --name=Nudge --windowed --onefile --icon=assets/icon.ico --add-data="assets;assets" app/main.py
# Use build.py instead (cross-platform, updates version automatically)

import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent
ASSETS_DIR = PROJECT_ROOT / "assets"
VERSION_FILE = PROJECT_ROOT / "file_version_info.txt"
ICON_FILE = ASSETS_DIR / "icon.ico"


a = Analysis(
    ['app/main.py'],
    pathex=[str(PROJECT_ROOT)],
    binaries=[],
    datas=[(str(ASSETS_DIR), 'assets')],
    hiddenimports=[
        'winreg', 'ctypes', 'sqlite3', 'json',
        'app.ui.mascot', 'app.ui.charts', 'app.ui.widgets', 'app.ui.theme',
        'app.ui.stats_window', 'app.ui.settings_window', 'app.ui.main_window',
        'app.ui.popup', 'app.ui.icons', 'app.controller', 'app.reminder',
        'app.settings', 'app.database', 'app.sound', 'app.tray',
        'app.autostart', 'app.paths', 'app.single_instance', 'app.updater',
        'app.version'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Nudge',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version=str(VERSION_FILE) if VERSION_FILE.exists() else None,
    icon=[str(ICON_FILE)] if ICON_FILE.exists() else [],
)
